version: '2'
services:

  postgres:
    restart: always
    image: postgres:9.6
    volumes:
      - /var/lib/postgresql

  web:
    image: slack-client
    command: ./docker-entrypoint-web.sh
    ports:
      - "1111:8000"
    links:
      - postgres
      - rabbitmq
    depends_on:
      - postgres

  rabbitmq:
    image: rabbitmq:3.6-management
    hostname: 'rabbitmq'
    ports:
      - "5672:5672"
    restart: always

  celery_worker:
    image: slack-client
    command: ./run_celery_worker.sh
    environment:
      - C_FORCE_ROOT=1
    links:
      - postgres
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes_from:
      - web

  celery_worker_files:
    image: slack-client
    command: ./run_celery_worker_files.sh
    environment:
      - C_FORCE_ROOT=1
    links:
      - postgres
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes_from:
      - web

  celery_beat:
    image: slack-client
    command: ./run_celery_beat.sh
    links:
      - postgres
      - rabbitmq
    depends_on:
      - rabbitmq
    volumes_from:
      - web
    restart: always

  celery_flower:
    image: slack-client
    command: ./run_celery_flower.sh
    ports:
      - "1112:5555"
    links:
      - rabbitmq
      - postgres
    depends_on:
      - celery_worker
      - celery_worker_files
    environment:
      - C_FORCE_ROOT=true
      - DATABASE_HOST=postgres
    volumes_from:
      - web
    restart: always